### ISSUE TITLE
soroban-cli: --list prints out cli and duplicate names

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-cli#1102] opened 2023-11-25 03:54 UTC
### What version are you using?

7f8ad60b9921b43871b2a5ec7e4d9494b909446f

### What did you do?

```console
$ soroban --list
```

### What did you expect to see?

A list of any plugins I have installed, where each is listed once. Or an empty list.

### What did you see instead?

```
❯ soroban --list
Installed Plugins:
    cli
    cli
```

### Discussions

It's odd that cli is included twice.

It's also odd that cli is included at all, since it isn't a plugin, it is the main tool.

**Comment by janewang** [comment] 2024-07-09 22:23
I can't reproduce this anymore. Closing

**Closed by janewang** 2024-07-09 22:23 UTC
Labels: bug, cli
