### ISSUE TITLE
while installing stellar-cli Error : can't find crate for `hyper`

### ISSUE THREAD

**Issue by happylucktoday** [stellar/stellar-cli#1399] opened 2024-06-24 03:07 UTC
### What I did

I was installing stellar-cli
I used command cargo install --locked stellar-cli
while it is compiling I faced an error:
error[E0463]: can't find crate for hyper
and so many errors related with 'hyper'
I don't understand what issue there is. 
![Uploading Screenshot_95.png…]()

**Comment by willemneal** [comment] 2024-06-24 11:20
Thanks for letting us know. 

Does the following work?

```

cargo install --locked cargo-binstall
cargo binstall -y stellar-cli

```
Also
What OS are you on?

**Comment by janewang** [comment] 2024-06-25 15:45
`rustc --explain E0463`


A crate was declared but cannot be found.
extern crate foo; // error: can't find crate

You need to link your code to the relevant crate in order to be able to use it (through
Cargo or the -L option of rustc, for example).

Common causes
*   The crate is not present at all. If using Cargo, add it to [dependencies]
     in Cargo.toml.
*   The crate is present, but under a different name. If using Cargo, look for package
    =  under [dependencies] in Cargo.toml.

Common causes for missing std or core
*   You are cross-compiling for a target
    which doesn't have std prepackaged. Consider one of the following: + Adding
    a pre-compiled version of std with rustup target add + Building std from
    source with cargo build -Z build-std + Using #![no_std] at the crate root,
    so you won't need std in the first place.
*   You are developing the compiler itself and haven't built libstd from source. You
    can usually build it with x.py build library/std. More information about
    x.py is available in the rustc-dev-guide.

**Comment by happylucktoday** [comment] 2024-07-10 18:16
I am using windows 10
When I try install, it works.
I tried a hello-world project on soroban test net
It works once, then doesn't work.
If I try several times, it is working well, then does not work
What is the issue?
Is is related with upload/download speed?
I tried on VPS, but I can not install rust
Please help me

**Comment by willemneal** [comment] 2024-07-10 19:03
So the install is working, but when using the CLI it fails?

If so what errors are you getting?

**Comment by janewang** [comment] 2024-07-11 02:24
So on your Windows 10, you have rust and the project is working. Worst case, you can remove the current `hello-world` project and restart here https://developers.stellar.org/docs/build/smart-contracts/getting-started/hello-world.

For the VPS, not sure why you cannot install rust and not sure what the OS is, but you could check try this way: https://www.rust-lang.org/tools/install

**Comment by happylucktoday** [comment] 2024-07-11 14:34
> So the install is working, but when using the CLI it fails?
> 
> If so what errors are you getting?

Can we have a discussion about stellar on discord?

**Comment by happylucktoday** [comment] 2024-07-11 14:35
> So on your Windows 10, you have rust and the project is working. Worst case, you can remove the current `hello-world` project and restart here https://developers.stellar.org/docs/build/smart-contracts/getting-started/hello-world.
> 
> For the VPS, not sure why you cannot install rust and not sure what the OS is, but you could check try this way: https://www.rust-lang.org/tools/install

Can we have a discussion about stellar on discord?
My id is @topmount2024

**Comment by leighmcculloch** [comment] 2024-07-12 02:24
@happylucktoday There's an ongoing discussion about this issue on Discord here:
- https://discord.com/channels/897514728459468821/1254628534228484097/1254628534228484097

As the issue appears to be environmental (i.e. caused by the system setup) I'm going to close the issue as it doesn't sound like a problem with the CLI itself. If it turns out that was the wrong call we can reopen this issue or a new issue.

**Closed by leighmcculloch** 2024-07-12 02:24 UTC
Labels: bug
